dist: xenial
language: python
addons:
  apt:
    packages:
    - libsnmp-dev
script:
- python3 setup.py install
before_deploy:
- git stash --all
- sed -i "s/@@version@@/${TRAVIS_TAG}/g" setup.py
deploy:
  skip_cleanup: true
  provider: pypi
  user: datagutten
  password:
    secure: Hk8gM2GDxyUQXG8Ep2sDNamKUAAGlqZTYei1JuhFgXHGK+P3fo3hVmriEeYSj8aKH/5kn+rRgQW4a6bG2ygdmk41T2kRJyg5D3y5FiuTKlzSWMMcqheo5JPyET/1hg3oJiPjdScKOnVMy53ldkZXm8sf6nd39RXhfFrayJpj74ryyuNVdTLfNHXK0gtYvC1VviBFygc3ScvTG6EYswS7Bz606tx4fjGrwnZEoAG8V2VLbKgvNAojjolxlRvYgA8QXouMHzGQQm6PTMlYAZp3jZGoVyh2ZqALBXnVij1/AItKhbdF1GlAuAQ1Rino0QO83oc4uxbvp0n/ERVMAdgaHRjCAGNn9HnkJCA7FDSW9PISzVSLgYd7j73G5N5CYwoMkoZv6HNK7CiRNchHtHWhArek6+T77yDOXe1KDDm3QpLsVMkmLIE75VI7c/7My+sI6NxE5WDcgT2OaIvtquTx0yZiMfuUBBpee5Nd1gsDQlR9AqmoyiGpQlfOznH0ViuTPhJxTEacMJy4GHpuqJGyi5bjg/mdj8MwKIQXb7ggG6u3SIT8wntTIcD3bm0QZGKe6JzmEBbLA5pnobFwiEmoZCR3MmtOvHPh56Do9fpjX0c1rIuBQok049p1ia5CYO3uaf5dK2opkWLyWQVVYg1PMij587iBEEeEvSbuF/Yf0wg=
  on:
    tags: true
  skip_existing: true
