dist: xenial
language: python
addons:
 apt:
  packages:
   - libsnmp-dev
script:
- python3 setup.py install
before_deploy:
- git stash --all
- sed -i "s/@@version@@/${TRAVIS_TAG}/g" setup.py
deploy:
  skip_cleanup: true
  provider: pypi
  user: datagutten
  password:
    secure: U9dp6nNbRg8kGEizl6qep1j3UT+3wO+PTqR0OJ7DmTFJffOBMNsSPbdPlVZyT0EFtGU0Da02wopCOsfzWLDHZQdBCGi35mrJE0Nitok0MjPx7uA6f8JcAxgAqc9fgtFykqmwRb3eej22VyB8y1tjl/+ur3/o8myRCiqF5TLfWXPbndZ1WgQPjD6nh9Ct+UsHyBb5VxjojrA9UEZ1tvKKgIJIYR0zKfb/v7KnL6dodAuM77L7daWbQ9tvQjPJd3WmOfsWXGdGxs+iDnvUPLLbnfVVWaXUdY1zvVWX3T5klHJf9U2DhUbOwbO2F343xW+8Z3Mc5U225QkM0EGNLVqjWp1vWGSAvB9q57OO7G8cPeAb5DK0gkQrifr+8Ku7iJakJMCvmjHebiEHcpCb2lma/HEGu4l95Qi2SRHt9GRTBgc1H7BO7PKZL8LIFClY9LfOlHOTxFFGELNlMNcd12zb/H1+C0OiFRtlcByR5pMtBO0Zj31QR1YYOo40GxxX7yMtQ/4cOQA1+bwgdpIfZdgtHUhXABmBZOAn9bFPGQQcDkgElUAapVnI/5bNFW11xqrvAr9ujAAoR896KZwz+NYsxBB2jt1xHbDYlN6sVe6+n1kq8UAutDxdHRmCaCVX7VXJyLrfsXbIfbd0CE2+eSaQjWZJJPv0XAPy4H1KwT3xNbs=
  on:
    tags: true
  skip_existing: true
